Algoritmo "ESTRTUTURACONDICIONALCOMPOSTAGLICOSE"

Var

   glicose : real

Inicio

   escreva ("Digite a medida da glisoce: ")
   leia (glicose)

   Se glicose <= 100.00 entao
      escreval ("Classificação: Normal")
   senao
      Se glicose <= 140.0 entao
         escreval ("Classificação: Elevado")
      senao
         escreval("Classificação: Diabetes")
     fimse
   fimse
   



Fimalgoritmo