Algoritmo "ESTRTUTURAREPETITIVAENQUANTOCRESCENTE"

Var

   x, y: inteiro

   
Inicio

   escreval ("Digite dois números: ")
   leia (x)
   leia (y)
   
   enquanto x <> y faca
   
   Se x < y entao
      escreval ("CRESCENTE")
   senao
      escreval ("DECRESCENTE")
   fimse
   
   escreval ("Digite outros dois números:")
   leia (X)
   leia (Y)
   
   fimenquanto

   
fimalgoritmo